language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/spec run --format=pretty --no-interaction
